# Generated by Django 5.1.3 on 2025-05-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_image_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(default='events_images/default.jpg', upload_to='events_images/'),
        ),
    ]
